name: API Deployment

on:
  push: 
    branches:
      - main

jobs:
    prepare-application:
      runs-on: ubuntu-latest
      container: 
        image: node:22
      defaults:
        run:
          working-directory: ./mes-api
      steps:
        - uses: actions/checkout@v3
          with:
            node-version: 22
        - run: npm i
        - run: npm run build
