name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:  
  deploy:  
    runs-on: self-hosted  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v4  
      - name: Set up Node.js  
        uses: actions/setup-node@v2  
        with:  
          node-version: 20.x 
      - name: Install dependencies  
        run: cd mes-api; npm i
      - name: Env check
        run: cd mes-api; ls 
      - name: Start Server
        run: cd mes-api; npm run dev
